### PR TITLE
Maintenance/Update MOM6

### PR DESCRIPTION
**Pull request by sanAkel**
This PR adjust [CMakeLists.txt](MOM6_GEOSPlug/mom6_cmake/CMakeLists.txt) to be able to work with updates from [MOM6 PR 1599](https://github.com/mom-ocean/MOM6/pull/1599)

**To do**:
- ✅ @sanAkel: once [pr1599](https://github.com/mom-ocean/MOM6/pull/1599) has been merged _undraft_ this PR.
- @GEOS-ESM/cmake-team (@mathomp4 and/or @tclune) review this PR. Thanks!

### CODE REVIEW

**Review by mathomp4 — APPROVED** [review]

**Comment by sanAkel** [comment]
We know that this will not run the tests (automatically), @mathomp4 please help. Thanks!

cc: @GEOS-ESM/cmake-team

**Review by tclune — APPROVED** [review]
cmake changes ok

**Comment by sanAkel** [comment]
@mathomp4 Anyway these checks can pass? Or use your powers to merge it?

**Comment by mathomp4** [comment]
> @mathomp4 Anyway these checks can pass? Or use your powers to merge it?

Oh. No. Probably not. The CI is looking for files it can never find. I can super power it in if you give me the green light.

**Comment by mathomp4** [comment]
Also: Should I sync up the MOM6 fork at the same time?

**Comment by sanAkel** [comment]
> Also: Should I sync up the MOM6 fork at the same time?

@mathomp4 Please bring on your _powers_ 😄 and also sync the fork! Thank you!

**Comment by mathomp4** [comment]
Merging with superpowers since CI can't work.

**Comment by mathomp4** [comment]
@sanAkel I've also synced up MOM6.

**Comment by sanAkel** [comment]
Awesome! Thank you!

**Pull request merged**
