### PR TITLE
Routine maintenance/update

### PR DESCRIPTION
**Pull request by sanAkel**
This PR updates MOM6_GEOSPlug/mom6_cmake/CMakeLists.txt 
No change in answers for GEOS.

Contingencies:
- https://github.com/mom-ocean/MOM6/pull/1611
- https://github.com/mom-ocean/MOM6/pull/1610

To do:
- @sanAkel undraft.
- @mathomp4 update GEOS fork of MOM6.

### CODE REVIEW

**Comment by sanAkel** [comment]
@mathomp4 one more request!

Please update GEOS fork of MOM6 when you have a moment. Thank you!

**Comment by mathomp4** [comment]
> @mathomp4 one more request!
> 
> Please update GEOS fork of MOM6 when you have a moment. Thank you!

This has been done. Hopefully if #47 passes its CI, when it's merged, you can update this branch and all will work.

**Review by tclune — APPROVED** [review]
CMake changes ok.

**Comment by sanAkel** [comment]
@zhaobin74, @yvikhlya can you guys take a look/review this?

**Review by yvikhlya — APPROVED** [review]

**Pull request merged**
