### PR TITLE
House cleaning of configurations

### PR DESCRIPTION
**Pull request by sanAkel**
This PR:

- Gets rids of dysfunctional configurations (i.e., `360x210` and `360x320` resolutions).
- Make use of WOA version 2018 (WOA18) as defaults, therefore no need to _override_ via `MOM_override`.

### CODE REVIEW

**Comment by mathomp4** [comment]
The coupled tests are not happy. Do I need to change things at low res in my BCs set?

**Comment by zhaobin74** [comment]
> The coupled tests are not happy. Do I need to change things at low res in my BCs set?

Maybe because "woa18_decav_t01_04.nc" file is not present? It needs to be linked/copied in gcm_run.j.

**Comment by mathomp4** [comment]
> > The coupled tests are not happy. Do I need to change things at low res in my BCs set?
> 
> Maybe because "woa18_decav_t01_04.nc" file is not present? It needs to be linked/copied in gcm_run.j.

Ah. Okay. I'm on leave until next week, so I'll try and get things fixed up then. @zhaobin74 where is this file located on discover so I can include it in TinyBCs?

**Comment by sanAkel** [comment]
@mathomp4, @zhaobin74 and all,

Please do following in your `gcm_run.j` (for now, **later**, I'll coordinate with @biljanaorescanin to have these files populated in the `BCs` path .and. patch the [App](https://github.com/GEOS-ESM/GEOSgcm_App)); see below(*)

```
set             FILE = linkbcs
/bin/rm -f     $FILE 
cat << _EOF_ > $FILE
#!/bin/csh -f
...
...
...

cp /discover/nobackup/sakella/woa18/1-deg/WOA18_decav_TPOTS_monthly_fulldepth_01.nc INPUT
```

**That gets a _full_depth_ WOA18 T and S file into `scratch/INPUT`.** 

(*) Reason for not patching the [App](https://github.com/GEOS-ESM/GEOSgcm_App) at this moment is so as to get @biljanaorescanin's help (as needed) in order to copy files from ⬆️ path **and** purge whats not needed.

I can successfully run with my `WOA18_decav_TPOTS_monthly_fulldepth_01.nc`, so I expect you can as well.

**Comment by mathomp4** [comment]
@sanAkel I can't see the file (rw only for you), but... 900MB. Ouch. 

Maybe once I can see inside it, I can work with you to prune it down for TinyBCs (i.e., if it's a daily file or something, we can pull out just a few days).

**Comment by sanAkel** [comment]
That (cut size) can be done. See in about an hour.

**Comment by sanAkel** [comment]
@mathomp4 I have undrafted this PR (again)! I don't want to hold off this clean up anymore (until I get a coarser WOA initial conditions. When we spoke last week, you said that the file size is ok.)

@zhaobin74 can you please review this PR.

Thanks!

**Comment by mathomp4** [comment]
Yay it's working!

**Comment by mathomp4** [comment]
Yay it worked! :)

**Comment by zhaobin74** [comment]
> Yay it worked! :)
@mathomp4, you mean it worked for c12x5 setup, right?

**Comment by mathomp4** [comment]
> > Yay it worked! :)
> > @mathomp4, you mean it worked for c12x5 setup, right?

Yes. Mainly that the CI didn't crash like before. The ocean could be boiling for all I know, but it ran for 6 hours! 😄

**Comment by zhaobin74** [comment]
> > > Yay it worked! :)
> > > @mathomp4, you mean it worked for c12x5 setup, right?
> 
> Yes. Mainly that the CI didn't crash like before. The ocean could be boiling for all I know, but it ran for 6 hours! 😄

Thanks, @mathomp4. I am testing the other two configs, 1440x1080 and 540x458.

First, 1440x1080 didn't work out of the box. 

>```cp /discover/nobackup/sakella/woa18/1-deg/WOA18_decav_TPOTS_monthly_fulldepth_01.nc INPUT``` 

failed with ```permission denied``` error.  

I see there is another (smaller) file ```/discover/nobackup/sakella/woa18/1-deg/WOA18_decav_TPOTS_mon01_fulldepth_01.nc```. Is this one supposed to be used? In that case, ``` 

 

> > > Yay it worked! :)
> > > @mathomp4, you mean it worked for c12x5 setup, right?
> 
> Yes. Mainly that the CI didn't crash like before. The ocean could be boiling for all I know, but it ran for 6 hours! 😄

Thanks, @mathomp4. I can test the other two configs, 1440x1080 and 540x458.

**Comment by zhaobin74** [comment]
First, 1440x1080 didn't work out of the box. 

>```cp /discover/nobackup/sakella/woa18/1-deg/WOA18_decav_TPOTS_monthly_fulldepth_01.nc INPUT``` 

failed with ```permission denied``` error.  

I see there is another (smaller) file ```/discover/nobackup/sakella/woa18/1-deg/WOA18_decav_TPOTS_mon01_fulldepth_01.nc```. Is this one supposed to be used? In that case, ```1440x1080/MOM_input``` should be updated to this new file.

**Comment by zhaobin74** [comment]
540x458  config works out of the box with ```/discover/nobackup/sakella/MOM6-GFDL/MOM6-testing/Gustavo.Marques/datasets/woa18_04_initial_conditions.nc```

**Comment by sanAkel** [comment]
> /discover/nobackup/sakella/woa18/1-deg/WOA18_decav_TPOTS_monthly_fulldepth_01.nc

@zhaobin74 thanks for testing both configurations:
1. `1440x1080` I fixed the file permission issue. Sorry, somehow I overlooked it! Whenever I `scp` files from local mac ➡️ discover, this happens.

> -rw-r--r-- 1 sakella s2640 908M Oct  4 18:24 /discover/nobackup/sakella/woa18/1-deg/WOA18_decav_TPOTS_monthly_fulldepth_01.nc

**Reg**:

> I see there is another (smaller) file /discover/nobackup/sakella/woa18/1-deg/WOA18_decav_TPOTS_mon01_fulldepth_01.nc. Using this file worked.
Is this one supposed to be used? 

**NO**. I want to use for this coarse- resolution tests only.

> In that case, 1440x1080/MOM_input should be updated to this new file.

⬆️  Not needed since I fixed the file permissions. 

2. `540x458` 

> config works out of the box
👍  Thanks!

**Comment by sanAkel** [comment]
@zhaobin74 can You please retry `1440x1080`?

**Comment by sanAkel** [comment]
@mathomp4 can you approve the PR since it seems to have worked for you.

**Review by mathomp4 — APPROVED** [review]

**Comment by mathomp4** [comment]
> @mathomp4 can you approve the PR since it seems to have worked for you.

Approved. Though without Yury, once @zhaobin74 approves I might have to use superpowers to get it in.

**Comment by zhaobin74** [comment]
> @zhaobin74 can You please retry `1440x1080`?

After the permission fix, 1440x1080 config is working:smiley:

**Review by zhaobin74 — APPROVED** [review]

**Comment by sanAkel** [comment]
> > @mathomp4 can you approve the PR since it seems to have worked for you.
> 
> Approved. Though without Yury, once @zhaobin74 approves I might have to use superpowers to get it in.

Yes @mathomp4 please use them! 😄

**Pull request merged**
