### PR TITLE
Feature/atrayano/mit config gmready

### PR DESCRIPTION
**Pull request by atrayano**

### CODE REVIEW

**Review by amolod — APPROVED** [review]
All changes are ok

**Review by sanAkel — COMMENTED** [review]
Since all changes are localized to MITgcm, I expect answers are unchanged for all else: MOM5 and MOM6.

Please confirm that is the case.

Thanks!

**Comment by atrayano** [comment]
Yes, the latest changes affect only MITgcm, and the are zero diff for MOM and MOM6. 

However, the previous PR (#26) makes impossible to merge to develop. I'll be working with @mathomp4 to fix this. The issue is that the CMakeList.txt refers to files in MOM6 that are not in the version of MOM6 referred by components.yaml

**Comment by mathomp4** [comment]
@sanAkel are you happy with me superpowering this in?

Once we do, we should probably then do a `develop` → `main` PR, and make releases of Ocean and MOM6.

**Comment by atrayano** [comment]
@sanAkel , after talking to @mathomp4 this morning, he suggested the following plan: he could use github super-powers to merge my PR (#27) to develop. After that, you need you to do 2 things:
1) create a release of MOM6 
2) create a release of OceanGridComp
Then I will create a PR of GEOSgcm fixture to reflect the updated versions of MOM6, and OceanGridComp, and also independent of all this, we need a newer tag of MITgcm

Matt is waiting for your OK of this plan before he merges PR#27

**Comment by sanAkel** [comment]
> @sanAkel are you happy with me superpowering this in?
> 
> 
> 
> Once we do, we should probably then do a `develop` → `main` PR, and make releases of Ocean and MOM6.
> 
> 
> 
> Also, I think @atrayano needs a new tag of MITgcm in fixture `components.yaml` so that needs an Ocean release as well

@mathomp4 Go ahead! Thanks for asking.

**Comment by mathomp4** [comment]
Superpowered in! Thanks @sanAkel

**Pull request merged**
