### PR TITLE
v2: Remove DEFAULT_2018_ANSWERS as obsolete

### LINKED ISSUE #77: Crash with 'FATAL from PE     0: MOM_obsolete_params'
Coupled run with MOM6 at 1440x1080 resolution crashed in MOM6 initializer:
```
WARNING from PE     0: MOM_obsolete_params: ETA_TOLERANCE_AUX is an obsolete run-time flag.


WARNING from PE     0: MOM_obsolete_params: ETA_TOLERANCE_AUX is an obsolete run-time flag.


WARNING from PE     0: MOM_file_parser : DEFAULT_2018_ANSWERS over-ridden.  Line: 'DEFAULT_2018_ANSWERS = False' in file MOM_override.


WARNING from PE     0: MOM_file_parser : DEFAULT_2018_ANSWERS over-ridden.  Line: 'DEFAULT_2018_ANSWERS = False' in file MOM_override.


FATAL from PE     0: MOM_obsolete_params: DEFAULT_2018_ANSWERS is an obsolete run-time flag, and should not be used. Instead use DEFAULT_ANSWER_DATE.


FATAL from PE     0: MOM_obsolete_params: DEFAULT_2018_ANSWERS is an obsolete run-time flag, and should not be used. Instead use DEFAULT_ANSWER_DATE.

--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on

``` 

```DEFAULT_2018_ANSWERS``` is not being accepted, but present in both ```MOM_input``` and ```MOM_override```.
It should be commented out or removed from both config files.

GEOS version: 11.6.0

### PR DESCRIPTION
**Pull request by mathomp4**
This is a v2 PR for #77 which removes `DEFAULT_2018_ANSWERS`

Closes #77

### CODE REVIEW

**Comment by zhaobin74** [comment]
Thanks, @mathomp4. It works.
@sdrabenh should get this update for his next release.

**Comment by mathomp4** [comment]
@zhaobin74 I'll work on getting a new tag out for @sdrabenh tomorrow I hope. 

I guess one other question: do you want the latest MOM6? I did merge in https://github.com/mom-ocean/MOM6/pull/1631 into our fork a couple weeks ago but I didn't make a release.

But since, well, you are the main Ocean dev at this time I suppose, if you like, I can make one and then promote it up the chain. I would be non-zero-diff unless a couple things are set, see https://github.com/mom-ocean/MOM6/pull/1631#issuecomment-2252914251

**Comment by mathomp4** [comment]
> @mathomp4, thanks for keeping our fork of MOM6 up to date. Over the long term, I think, it is always beneficial to keep running with the latest version, especially if there is bug fix or new feature needed. For now, we can update MOM6 with those 2 new options to be zero-diff. I am fine with it.

@zhaobin74 Sooooo...how would one do that? I mean, I sort of figured something out so I could give @marshallward a thumbs up, but I'm sure I did it in a very heavy-handed manner. What would be the "right" way in GEOS land? Would I/we add lines to the `MOM_override` files? Or `MOM_input`?

**Comment by zhaobin74** [comment]
> > @mathomp4, thanks for keeping our fork of MOM6 up to date. Over the long term, I think, it is always beneficial to keep running with the latest version, especially if there is bug fix or new feature needed. For now, we can update MOM6 with those 2 new options to be zero-diff. I am fine with it.
> 
> @zhaobin74 Sooooo...how would one do that? I mean, I sort of figured something out so I could give @marshallward a thumbs up, but I'm sure I did it in a very heavy-handed manner. What would be the "right" way in GEOS land? Would I/we add lines to the `MOM_override` files? Or `MOM_input`?

Yes, we can add them in ```MOM_override```. So an ```OceanGridComp``` update needs go along with ```MOM6```.

**Comment by mathomp4** [comment]
> Yes, we can add them in `MOM_override`. So an `OceanGridComp` update needs go along with `MOM6`.

Okay. I might work with you Monday on that to make sure I do it right.

**Comment by mathomp4** [comment]
This PR in combination with #81 and with MOM6 geos/v3.2 is zero-diff to current MOM6.

**Pull request merged**
