### PR TITLE
Update MOM6 after https://github.com/mom-ocean/MOM6/pull/1556 is merged

### PR DESCRIPTION
**Pull request by sanAkel**
This PR originates from [GEOS-ESM/GEOSgcm_GridComp](https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/531). Below is the relevant copy/paste from there:

In order for [GEOS-ESM](https://github.com/GEOS-ESM) to use [MOM6 release geos/v2.0.3](https://github.com/GEOS-ESM/MOM6/tree/geos/v2.0.3) following sequence of steps need to happen in this order:

This PR updates:
- MOM6 `cMakeLists.txt` (because a few extra files have been added).
- All [configs of MOM6 for GEOS](https://github.com/GEOS-ESM/GEOSgcm_GridComp/tree/develop/GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app) have been updated/sync'ed in with the defaults expected in [MOM6 release geos/v2.0.3](https://github.com/GEOS-ESM/MOM6/tree/geos/v2.0.3).

PR in [GEOSgcm](https://github.com/GEOS-ESM/GEOSgcm) to uptick MOM6 [version number to geos/v2.0.3](https://github.com/GEOS-ESM/GEOSgcm/blob/main/components.yaml) would need to be added, **after this PR is merged**.

@mathomp4, @sdrabenh heads up: for known reasons (bugfixes and improvements: changes in default values of parameters, see https://github.com/mom-ocean/MOM6/pull/1556) this code will be non-zero difference (from the way we currently run). Affects only the MOM6 based GEOS AOGCM. I would certainly need your help with above (PR in GEOSgcm). 🙏

### CODE REVIEW

**Review by yvikhlya — DISMISSED** [review]

**Review by mathomp4 — APPROVED** [review]
CMake good.

**Comment by mathomp4** [comment]
Blocking for a second. The CI seems...weird.

**Review by tclune — APPROVED** [review]
cmake changes ok.

@mathomp4 - I wonder if we should deactivate the cmake team for mom6 as this is now GFDL code?

**Comment by mathomp4** [comment]
> cmake changes ok.
> 
> @mathomp4 - I wonder if we should deactivate the cmake team for mom6 as this is now GFDL code?

@tclune No. This is *our* cmake code for MOM6 (the plugs, gridcomps, cmake, etc.). Though I suppose if we get to a place where we can use MOM's cmake directly, we might be able to remove some...

**Pull request merged**
