### PR TITLE
Update MOM6: routine maintenance-2022-11-10

### PR DESCRIPTION
**Pull request by sanAkel**
This PR updates GEOS- MOM6 [CMakeLists.txt](https://github.com/GEOS-ESM/GEOS_OceanGridComp/blob/develop/MOM6_GEOSPlug/mom6_cmake/CMakeLists.txt) to be consistent with https://github.com/mom-ocean/MOM6/pull/1586 once that is merged.

This PR **changes answers** because of community agreed upon change in MOM6 defaults, **impacts only the MOM6 based GEOS coupled model**.

Steps to follow:
- @sanAkel undraft this PR when @marshallward merges https://github.com/mom-ocean/MOM6/pull/1586
- @mathomp4 and/or @tclune please review
- @mathomp4 please use your powers to merge and update our MOM6 fork.

Thank you!

### CODE REVIEW

**Comment by mathomp4** [comment]
@sanAkel It looks like @marshallward did the merge. If all is good for you, I can update the fork.

**Comment by sanAkel** [comment]
> @sanAkel It looks like @marshallward did the merge. If all is good for you, I can update the fork.

@mathomp4 Please go ahead with the update. However, until the @GEOS-ESM/cmake-team approves, the `CMakeLists.txt` will be **inconsistent** with the updated source code.

If possible, first review the PR and then merge. Thanks!

**Review by mathomp4 — APPROVED** [review]

**Comment by mathomp4** [comment]
> > @sanAkel It looks like @marshallward did the merge. If all is good for you, I can update the fork.
> 
> @mathomp4 Please go ahead with the update. However, until the @GEOS-ESM/cmake-team approves, the `CMakeLists.txt` will be **inconsistent** with the updated source code.
> 
> If possible, first review the PR and then merge. Thanks!

@sanAkel I did both. Obviously, you'll need/want to make a release of MOM6 so you eventually component-ize this.

**Comment by sanAkel** [comment]
Great! Thanks!!

Looks like I can't merge, would you please do it ?

**Pull request merged**
