### PR TITLE
Maintenance/Update MOM6

### PR DESCRIPTION
**Pull request by sanAkel**
This PR adjusts [CMakeLists.txt](https://github.com/GEOS-ESM/GEOS_OceanGridComp/pull/MOM6_GEOSPlug/mom6_cmake/CMakeLists.txt) to be able to work with updates from this  [PR](https://github.com/mom-ocean/MOM6/pull/1616). 

Specifically, it adds following to the list of files that are to be built: `src/parameterizations/lateral/MOM_self_attr_load.F90`.

In GEOS default setting, answers are preserved. 

**To do:**

- [x] @sanAkel: https://github.com/mom-ocean/MOM6/pull/1616 once has been merged submit this PR.
- [x] @mathomp4 and/or @tclune: https://github.com/orgs/GEOS-ESM/teams/cmake-team please review this PR. 
- [x] @mathomp4: please update our fork: https://github.com/GEOS-ESM/MOM6

### CODE REVIEW

**Comment by mathomp4** [comment]
Hmm. the "update MOM6" is checked and yet I don't think I've done that recently. Shall I?

**Comment by sanAkel** [comment]
> Hmm. the "update MOM6" is checked and yet I don't think I've done that recently. Shall I?

Sorry @mathomp4 maybe pushing these from my phone messed it up. I just _unchecked_ those boxes. Once [PR 1616 at mom-ocean](https://github.com/mom-ocean/MOM6/pull/1616) gets merged, let's get it done at our end.

**Comment by sanAkel** [comment]
@mathomp4 would you please review this PR. Thanks!

**Review by mathomp4 — APPROVED** [review]

**Comment by mathomp4** [comment]
Superpowering in as this needs a new MOM6

**Pull request merged**
