### PR TITLE
Build time option for ocean model

### PR DESCRIPTION
**Pull request by sanAkel**
This PR:
- Introduces a build time option for ocean model; data ocean is always built. 
- Preserves answers.

**Example**:
If a user wants to build using `MOM5` ocean model, in addition to [these cmake options]() add: `-DGEOS_OCEAN=MOM5`; defaults are defined in a contingent PR. See ⬇️.

- Has contingencies:  
1. [GCM GC](https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/866)
2. [GCM App](??)

### CODE REVIEW

**Comment by sanAkel** [comment]
There is a dependency on mom6 library in `src/Applications/@UMD_Etc/UMD_oletkf/CMakeLists.txt `

```
esma_add_library (${this}
  SRCS ${SRCS}
  DEPENDENCIES **mom6** NetCDF::NetCDF_Fortran MPI::MPI_Fortran
  )
```

Because of above, one must always build GEOS with mom6, so build of **mom5--only** is not possible-- FYI: @mathomp4.

For now closing this PR, but noted for future.

**Comment by mathomp4** [comment]
> There is a dependency on mom6 library in `src/Applications/@UMD_Etc/UMD_oletkf/CMakeLists.txt `
> 
> ```
> esma_add_library (${this}
>   SRCS ${SRCS}
>   DEPENDENCIES **mom6** NetCDF::NetCDF_Fortran MPI::MPI_Fortran
>   )
> ```
> 
> Because of above, one must always build GEOS with mom6, so build of **mom5--only** is not possible-- FYI: @mathomp4.
> 
> For now closing this PR, but noted for future.

Well, if MOM5 is selected, we could just not build UMD_oletkf? If it's needed for mom5 as well, then we'd have to explore more.

**Comment by sanAkel** [comment]
> > There is a dependency on mom6 library in `src/Applications/@UMD_Etc/UMD_oletkf/CMakeLists.txt `
> > ```
> > esma_add_library (${this}
> >   SRCS ${SRCS}
> >   DEPENDENCIES **mom6** NetCDF::NetCDF_Fortran MPI::MPI_Fortran
> >   )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Because of above, one must always build GEOS with mom6, so build of **mom5--only** is not possible-- FYI: @mathomp4.
> > For now closing this PR, but noted for future.
> 
> Well, if MOM5 is selected, we could just not build UMD_oletkf? If it's needed for mom5 as well, then we'd have to explore more.

That: `not build UMD_oletkf` can work, because truth is, nobody is running that `UMD_oletkf`.

@mathomp4 if you have the time, please do make that `switch` in `UMD_oletkf` to turn off its build with mom6. Thank you!

**Comment by mathomp4** [comment]
@sanAkel So should I have UMD_oletkf build only with mom5 or only with mom6?

**Comment by sanAkel** [comment]
> @sanAkel So should I have UMD_oletkf build only with mom5 or only with mom6? 

@mathomp4 We should not build it at all :) recall, I had a PR to remove it?

Anyway only mom5, that code will never work with mom6.

**Pull request closed without merging**
