### PR TITLE
new GEOS-MITgcm configs that has shelfice

### PR DESCRIPTION
**Pull request by afahadabdullah**
a new experiment config for GEOS-MITgcm from eccov4r5.

### CODE REVIEW

**Review by sanAkel — APPROVED** [review]
This PR adds code/config that falls outside the scope of my work. In any case approving it to advance their work.

**Comment by mathomp4** [comment]
Note: I'm pretty sure the CI failures will abate once `develop` is merged into this branch via `Update branch`.

**Comment by sanAkel** [comment]
> Note: I'm pretty sure the CI failures will abate once `develop` is merged into this branch via `Update branch`.

@afahadabdullah will you do ⬆️ as @mathomp4 suggests.

**Comment by afahadabdullah** [comment]
> > Note: I'm pretty sure the CI failures will abate once `develop` is merged into this branch via `Update branch`.
> 
> @afahadabdullah will you do ⬆️ as @mathomp4 suggests.

**Comment by afahadabdullah** [comment]
> > Note: I'm pretty sure the CI failures will abate once `develop` is merged into this branch via `Update branch`.
> 
> @afahadabdullah will you do ⬆️ as @mathomp4 suggests.

@sanAkel yes, let me check with @mathomp4 how to do this. thanks, Santha.

**Comment by sanAkel** [comment]
@afahadabdullah you don't have to close this PR!

1. Reopen the PR
2. Push the button that says something like "merge with develop" and squash your commits or whatever you prefer.

**Pull request merged**
