### PR TITLE
Comment out daily output

### PR DESCRIPTION
**Pull request by sanAkel**
Resolves https://github.com/GEOS-ESM/GEOS_OceanGridComp/issues/62

Coarse resolution [diag_table](https://github.com/GEOS-ESM/GEOS_OceanGridComp/blob/develop/MOM6_GEOSPlug/mom6_app/72x36/diag_table) is left untouched, since it used for debugging/development.

### CODE REVIEW

**Comment by yvikhlya** [comment]
Can I suggest to make them monthly instead of commenting out? We need ocean diagnostics in coupled runs, right?

**Comment by sanAkel** [comment]
> May I suggest to make them monthly instead of commenting out? We need ocean diagnostics in coupled runs, right?

Done.

**Comment by yvikhlya** [comment]
One last thing, did you leave dailies for `sfc_ave` intentionally?

**Comment by sanAkel** [comment]
> @sanAkel One last thing, did you leave dailies for `sfc_ave` intentionally?

yes @yvikhlya Let's have those daily 2d fields for now.

**Comment by yvikhlya** [comment]
Ok.

**Review by yvikhlya — APPROVED** [review]

**Pull request merged**
